### ISSUE TITLE
Test the newly created simulation and fix errors

### ISSUE THREAD

**Issue by saranshbhardwaj** [ARA-Trans/iAM#323]
- [ ] Add remaining code to CreateNewSimulation to copy what is in the legacy app.
- [ ] Test to see if it runs a simulation to completion

**Comment by rbyrne2** [comment]
SP-1

**Comment by rbyrne2** [comment]
I checked and the 'new simulation' code actually matches the legacy app but does not run after being created. Branch 323 has code called 'CreateRunnableSimulation'  ,  since we are still trying to reproduce the old apps behavior do not want to delete the existing CreateNewSimulation.  Go ahead and work with it if it makes sense to be able to run the newly created simulation or delete the branch. I ran out of time.
